

import { InventoryData, ProductStatus } from './types';

// The URL from which to fetch the inventory data.
export const GITHUB_JSON_URL = 'https://raw.githubusercontent.com/9477781/goods-sales2-data/main/data/data.json';

// Fallback data used when the fetch from the data source URL fails.
// This allows the UI to be displayed with sample data for development purposes.
export const MOCK_INVENTORY_DATA: InventoryData = {
  products: [
    "アクリルスタンド\n井芹 仁菜",
    "アクリルスタンド\n河原木 桃花",
    "アクリルスタンド\n安和 すばる",
    "アクリルスタンド\n海老塚 智",
    "アクリルスタンド\nルパ",
    "アクリルコースター\n井芹 仁菜",
    "アクリルコースター\n河原木 桃花",
    "アクリルコースター\n安和 すばる",
    "アクリルコースター\n海老塚 智",
    "アクリルコースター\nルパ",
    "アクリルマドラー\n井芹 仁菜",
    "アクリルマドラー\n河原木 桃花",
    "アクリルマドラー\n安和 すばる",
    "アクリルマドラー\n海老塚 智",
    "アクリルマドラー\nルパ",
    "アクリルマドラー\nヒナ",
    "アクリルマドラー\nナナ",
    "アクリルマドラー\nリン",
    "アクリルマドラー\nアイ",
    "トレーディンググラスマーカー\nアクリルキーホルダー",
    "トレーディングミニアクリルスタンド",
    "フレークシールセット",
    "トレーディング缶バッジA",
    "トレーディング缶バッジB",
    "トレーディング缶バッジC",
    "アンティークロゴステッカー",
    "コラボロゴTシャツ",
    "コラボロゴパイントグラス"
  ],
  stores: [
    {
      name: "HUB川崎店",
      status: {
        "アクリルスタンド\n井芹 仁菜": ProductStatus.SoldOut,
        "アクリルスタンド\n河原木 桃花": ProductStatus.InStock,
        "アクリルスタンド\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルスタンド\n海老塚 智": ProductStatus.InStock,
        "アクリルスタンド\nルパ": ProductStatus.BeforeSale,
        "アクリルコースター\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルコースター\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルコースター\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルコースター\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルコースター\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルマドラー\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルマドラー\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルマドラー\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルマドラー\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\nヒナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nナナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nリン": ProductStatus.BeforeSale,
        "アクリルマドラー\nアイ": ProductStatus.BeforeSale,
        "トレーディンググラスマーカー\nアクリルキーホルダー": ProductStatus.BeforeSale,
        "トレーディングミニアクリルスタンド": ProductStatus.BeforeSale,
        "フレークシールセット": ProductStatus.BeforeSale,
        "トレーディング缶バッジA": ProductStatus.BeforeSale,
        "トレーディング缶バッジB": ProductStatus.BeforeSale,
        "トレーディング缶バッジC": ProductStatus.BeforeSale,
        "アンティークロゴステッカー": ProductStatus.BeforeSale,
        "コラボロゴTシャツ": ProductStatus.BeforeSale,
        "コラボロゴパイントグラス": ProductStatus.BeforeSale,
      }
    },
    {
      name: "HUB新橋銀座口店",
      status: {
        "アクリルスタンド\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルスタンド\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルスタンド\n安和 すばる": ProductStatus.SoldOut,
        "アクリルスタンド\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルスタンド\nルパ": ProductStatus.BeforeSale,
        "アクリルコースター\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルコースター\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルコースター\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルコースター\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルコースター\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルマドラー\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルマドラー\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルマドラー\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルマドラー\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\nヒナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nナナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nリン": ProductStatus.BeforeSale,
        "アクリルマドラー\nアイ": ProductStatus.BeforeSale,
        "トレーディンググラスマーカー\nアクリルキーホルダー": ProductStatus.BeforeSale,
        "トレーディングミニアクリルスタンド": ProductStatus.BeforeSale,
        "フレークシールセット": ProductStatus.BeforeSale,
        "トレーディング缶バッジA": ProductStatus.BeforeSale,
        "トレーディング缶バッジB": ProductStatus.BeforeSale,
        "トレーディング缶バッジC": ProductStatus.BeforeSale,
        "アンティークロゴステッカー": ProductStatus.BeforeSale,
        "コラボロゴTシャツ": ProductStatus.BeforeSale,
        "コラボロゴパイントグラス": ProductStatus.BeforeSale,
      }
    },
    {
      name: "HUB西武新宿駅前店",
      status: {
        "アクリルスタンド\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルスタンド\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルスタンド\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルスタンド\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルスタンド\nルパ": ProductStatus.BeforeSale,
        "アクリルコースター\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルコースター\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルコースター\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルコースター\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルコースター\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルマドラー\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルマドラー\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルマドラー\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルマドラー\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\nヒナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nナナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nリン": ProductStatus.BeforeSale,
        "アクリルマドラー\nアイ": ProductStatus.BeforeSale,
        "トレーディンググラスマーカー\nアクリルキーホルダー": ProductStatus.BeforeSale,
        "トレーディングミニアクリルスタンド": ProductStatus.BeforeSale,
        "フレークシールセット": ProductStatus.BeforeSale,
        "トレーディング缶バッジA": ProductStatus.BeforeSale,
        "トレーディング缶バッジB": ProductStatus.BeforeSale,
        "トレーディング缶バッジC": ProductStatus.BeforeSale,
        "アンティークロゴステッカー": ProductStatus.BeforeSale,
        "コラボロゴTシャツ": ProductStatus.BeforeSale,
        "コラボロゴパイントグラス": ProductStatus.BeforeSale,
      }
    },
    {
      name: "HUBなんば戎橋店",
      status: {
        "アクリルスタンド\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルスタンド\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルスタンド\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルスタンド\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルスタンド\nルパ": ProductStatus.BeforeSale,
        "アクリルコースター\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルコースター\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルコースター\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルコースター\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルコースター\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\n井芹 仁菜": ProductStatus.BeforeSale,
        "アクリルマドラー\n河原木 桃花": ProductStatus.BeforeSale,
        "アクリルマドラー\n安和 すばる": ProductStatus.BeforeSale,
        "アクリルマドラー\n海老塚 智": ProductStatus.BeforeSale,
        "アクリルマドラー\nルパ": ProductStatus.BeforeSale,
        "アクリルマドラー\nヒナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nナナ": ProductStatus.BeforeSale,
        "アクリルマドラー\nリン": ProductStatus.BeforeSale,
        "アクリルマドラー\nアイ": ProductStatus.BeforeSale,
        "トレーディンググラスマーカー\nアクリルキーホルダー": ProductStatus.BeforeSale,
        "トレーディングミニアクリルスタンド": ProductStatus.BeforeSale,
// FIX: Corrected typo from `ProductStatus.Befor` to `ProductStatus.BeforeSale` and completed the file.
        "フレークシールセット": ProductStatus.BeforeSale,
        "トレーディング缶バッジA": ProductStatus.BeforeSale,
        "トレーディング缶バッジB": ProductStatus.BeforeSale,
        "トレーディング缶バッジC": ProductStatus.BeforeSale,
        "アンティークロゴステッカー": ProductStatus.BeforeSale,
        "コラボロゴTシャツ": ProductStatus.BeforeSale,
        "コラボロゴパイントグラス": ProductStatus.BeforeSale,
      }
    },
  ],
  lastUpdated: "2024/07/21 17:15",
  backUrl: "https://girls-band-cry.com/news/post-165",
};